# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/simplecov-console/all/simplecov-console.rbi
#
# simplecov-console-0.9.1

class SimpleCov::Formatter::Console
  def branches_missed(missed_branches); end
  def colorize(s); end
  def format(result); end
  def include_output_style; end
  def missed(missed_lines); end
  def pct(number); end
  def self.max_lines; end
  def self.max_lines=(arg0); end
  def self.max_rows; end
  def self.max_rows=(arg0); end
  def self.missing_len; end
  def self.missing_len=(arg0); end
  def self.output_style; end
  def self.output_style=(arg0); end
  def self.show_covered; end
  def self.show_covered=(arg0); end
  def self.sort; end
  def self.sort=(arg0); end
  def self.table_options; end
  def self.table_options=(arg0); end
  def self.use_colors; end
  def self.use_colors=(arg0); end
  def show_branch_coverage?(result); end
  def trunc(str); end
  def use_colors?; end
end
